name: TogglePhantoms
version: '${version}'
main: dev.oakheart.togglephantoms.TogglePhantoms
description: 'Allows players to toggle phantom spawning for themselves.'
api-version: '1.21.10'
authors:
  - Loralon
website: https://github.com/LoralonMC/TogglePhantoms
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
